### ISSUE TITLE
No Data

### ISSUE THREAD

**Issue by ghost** [FortDigital/covid-19#5] opened 2020-03-25 16:17 UTC
Installed as described in readme.

Python : 3.6 
OS: Ubuntu 18.04
InfluxDB shell version: 1.7.10
Grafana: 6.7.1 

Running : ~/covid-19# python3 covid19.py

no error at all, but it shows no Data in some fields. 

![25-03-_2020_17-06-32](https://user-images.githubusercontent.com/621860/77558733-979fe680-6ebb-11ea-8f2d-dffafcc73036.png)

**Comment by FortDigital** [comment] 2020-03-27 15:56
This is most likely down to the change in File names from JHU, Ive pushed an updated version of the script (And dashboard) today that includes the new file names. can you let me know if that works?

**Comment by ghost** [comment] 2020-03-27 19:23
Got no idea, pulled origin master and tried it again. Now i got one field more with Data. As you can see, the table under the worldmap looks a bit strange. 

![gitscreen](https://user-images.githubusercontent.com/621860/77792451-aed00700-7068-11ea-89f9-5a75b6fad4d6.png)

**Comment by FortDigital** [comment] 2020-03-27 22:45
The bottom graphs look like they are pulling the wrong key values through from the fields variable set on the dashboard, can you check its pointing to your covid19 datasource?

![image](https://user-images.githubusercontent.com/62287745/77806430-94a02400-707c-11ea-8793-f3704bc28e76.png)

Check the Country variable is also pointing to the right datasource as that would affect some of the other boxes.

**Comment by ehsjoar** [comment] 2020-04-06 21:56
Hi,

I have the same issue. I think the issue is that you are hitting the wrong influx DB and that is why we see some strange keys

Cheers,

// Jonas

**Comment by ehsjoar** [comment] 2020-04-06 22:02
Hi Again,

So this is a problem on our side. We need to create a new data source with the right DB and pick that when we import the dashboard. Everything is working now. Thanks!

// Jonas

**Comment by FortDigital** [comment] 2020-04-07 07:24
Closing this issue as appears to be an issue with local grafana config

**Closed as completed by FortDigital** 2020-04-07 07:24 UTC
